DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE EVENTS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_USER_ID;
DROP SEQUENCE SEQ_EVENT_ID;

CREATE SEQUENCE SEQ_USER_ID NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT_ID NOCACHE NOCYCLE;



CREATE TABLE USERS (
    NO           NUMBER PRIMARY KEY
    , ID         VARCHAR2(50) NOT NULL
    , NAME       VARCHAR2(50) UNIQUE
    , PWD        VARCHAR2(100)
    , EMAIL      VARCHAR2(100)
);

-- 회원가입
INSERT INTO USERS (NO, ID, NAME, PWD, EMAIL) VALUES (SEQ_USER_ID.NEXTVAL, 'USER01', '홍길동', '1234', 'NAVER');

-- 로그인
SELECT * FROM USERS WHERE ID = 'USER01' AND PWD = '1234';

-- 회원정보 수정
UPDATE MEMBER SET PWD = ? WHERE ID = ?;

-- 회원 탈퇴
DELETE USER WHERE ID = ?;

CREATE TABLE EVENTS (
    EVENTNO         NUMBER
    , EVENTNAME     VARCHAR2(100)
    , CONTENT       VARCHAR2(100)
    , EVENTDATE     DATE
    , USERID        NUMBER
    , FOREIGN KEY (USERID) REFERENCES USERS(NO)
);

-- 이벤트 생성
INSERT INTO EVENTS (EVENTNO, EVENTNAME, CONTENT, EVENTDATE) 
VALUES (SEQ_EVENT_ID.NEXTVAL, '면접3', '000회사', TO_DATE('2024-04-01', 'YYYY-MM-DD'));

-- 이벤트 목록 전체 조회
SELECT EVENTNAME 일정, CONTENT 일정내용, EVENTDATE 날짜, USERID "유저 고유 번호"
FROM EVENTS
;

-- 이벤트 상세조회 (일정 이름)
SELECT *
FROM EVENTS
WHERE EVENTNAME LIKE '%면접%'
;

-- 이벤트 상세조회(월)
SELECT * 
FROM EVENTS 
WHERE TO_CHAR(EVENTDATE, 'MM') = '04'
;

SELECT * 
FROM EVENTS 
WHERE USERID = 1
;

SELECT EVENTNO, EVENTNAME,CONTENT,EVENTDATE 
FROM EVENTS 
ORDER BY EVENTNO ;
